# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1acd8a1102d30daa74f939079aa09bb6c0ce18eccabe1dbc10f0c82caf47ec883139e26e1b594f999cbf81c5a2a73b56d67090f6188521fb105e71f585bbd3f4

test:
  secret_key_base: 0c18886d60ef7ae366acc9a1fb85054cfb02610e6ab518e7bdc142c511cfa385c2fb07c75ac50e8933225d9887de9da6fe5b17e3a4d0de470c8101f6feea26dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
